### ISSUE TITLE
Spotify play not working.

### ISSUE THREAD

**Issue by cjabb** [brblacky/lavamusic#488]
i wanted to turn off youtube search for this bot and allow only spotify to work but it isnt, i tried disabling youtube sources from lavalink. Im using LavaSrc btw, it doesnt error out it just tried to add the song to the queue and play it but it fails with no errors in the console. Any help? 

application.yml file Lavalink
```
lavalink:
    plugins:
        - dependency: com.github.TopiSenpai.LavaSrc:lavasrc-plugin:3.2.9
          repository: https://maven.topi.wtf/releases
    server:
        bufferDurationMs: 400
        gc-warnings: true
        password: RolandC134
        playerUpdateInterval: 5
        soundcloudSearchEnabled: false
        sources:
            bandcamp: false
            http: false
            local: false
            soundcloud: true
            spotify: true
            twitch: false
            vimeo: false
            youtube: true
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        max-history: 30
        max-size: 1GB
    level:
        lavalink: INFO
        root: INFO
    path: ./logs/
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    lavasrc:
        applemusic:
            albumLoadLimit: 6
            countryCode: US
            mediaAPIToken: '...'
            playlistLoadLimit: 6
        deezer:
            masterDecryptionKey: your master decryption key
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1
            translate: false
            voice: default voice
        providers:
            - ytsearch:"%ISRC%"
            - ytsearch:%QUERY%
        sources:
            applemusic: false
            deezer: false
            flowerytts: false
            spotify: true
            yandexmusic: false
            youtube: true
        spotify:
            albumLoadLimit: 6
            clientId: SHHH
            clientSecret: NO LEAKS TODAY
            countryCode: US
            playlistLoadLimit: 6
        yandexmusic:
            accessToken: your access token
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    port: 25217
```
